spring:
  application:
    name: my-springboot
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
server:
  port: 8888
  servlet:
    context-path: /api
logging:
  level:
    root: error
    com.itlaoqi: debug
app:
  config:
    upload-addr: d:/upload
    app-key: 1111-2222-3333

